version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: blog.cronje.me-nginx
    ports:
      - '6000:80'
      - '6443:443'
    volumes:
      - "./nginx/:/etc/nginx/templates/"
      - "./certs:/etc/certs"
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
      - "DOMAIN=${DOMAIN}"
    depends_on:
      - wordpress
    restart: always

  mysql:
    # Uncomment the below line for m1 macs
    # platform: linux/x86_64
    image: mysql:8.0
    container_name: "blog.cronje.me-mysql"
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "4334.4334"
      MYSQL_DATABASE: "blog_cronje_me"
      MYSQL_USER: "cp"
      MYSQL_PASSWORD: "4334.4334"

  wordpress:
    depends_on: 
      - mysql
    image: wordpress:latest
    container_name: blog.cronje.me-wordpress
    restart: always
    volumes: 
      - ./wordpress:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_NAME: "blog_cronje_me"
      WORDPRESS_DB_USER: "cp"
      WORDPRESS_DB_PASSWORD: "4334.4334"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: blog.cronje.me-phpmyadmin
    volumes:
      - ./config/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
      MYSQL_ROOT_PASSWORD: "4334.4334"
    ports:
      - '6080:80'
    links:
      - mysql:mysql

